### PR TITLE
__file: rework

### PR DESCRIPTION
**Pull request by sideeffect42**
When trying to experiment with atomic file copies (possibly without `scp(1)`) I came to the conclusion that the age of the `__file` type really shows.  

So I did some modernisation first:
* use tabs for indentation everywhere
* add `:?` "guards" to cdist environment variables
* fix an ordering error when detecting symlinks
* try to make the logic in `gencode-*` more succinct.

I didn't yet extensively test the changes, but I still wanted to put the changes out for others to see, because the type is very important and more eyes see more.

### CODE REVIEW

**Comment by 4nd3r** [comment]
> use tabs for indentation everywhere

:angry:

**Comment by sideeffect42** [comment]
> > use tabs for indentation everywhere
> 
> 😠

😟

can we at least agree that tabs are better than 3 spaces?

I don't want to get into the tabs/spaces discussion, because there is no solution to it.
One, IMHO good, argument in favour of tabs is that they allow you to use "indented here-documents (`<<-`)" without having to switch indentation (e.g. [old](https://github.com/cdist-community/cdist-conf/pull/43/files#diff-cb6d7fc95cdb1993e29779cfc2aa493edb6b97ef47b6e14253ccdb555e68a4e0L123) vs [new](https://github.com/cdist-community/cdist-conf/pull/43/files#diff-cb6d7fc95cdb1993e29779cfc2aa493edb6b97ef47b6e14253ccdb555e68a4e0R62)).

**Comment by 4nd3r** [comment]
sorry, I'm in *Tabs Are Evil* party.

and instead of arguing, look how big boys are doing it and stop swimming against the current:
* https://www.kernel.org/doc/html/latest/process/coding-style.html
* https://google.github.io/styleguide/shellguide.html

but using tabs will not stop me reviewing (and approving) it, so please continue as you please. having *enter project name here* shell style guide is least of our problems, so for now, let's put our efforts into actual code writing.

**Comment by sideeffect42** [comment]
This PR was superseded by #94.

**Pull request closed without merging**
