### PR TITLE
[type/__locale_system+explorer/os_version] use /etc/locale.conf in trixie/sid, add forky

### PR DESCRIPTION
**Pull request by 4nd3r**

### CODE REVIEW

**Comment by sideeffect42** [comment]
:+1: for the change in `__locale_system` from my side.

I'm not sure about the change to `os_version`, however.
While `x.99` is not very informative it is an easy way to detect pre-release versions to e.g. not use `__apt_backports`.

I'm not opposing the removal of the `.99` "hack" per se, but I think there should be a way to differentiate testing versions.

Ideally this would be the same way to do so for different distros.
I didn't think it through in detail yet but maybe a new explorer (`release-quality` or something) could be added which prints something along the lines of:
* `(old)*stable`/`sid` for De??an,
* `release`/`edge` for Alpine,
* `rolling` for Gentoo, Arch etc.,
* `el`/`stream` for whatever CentOS and its derivatives feel like this week,
* `release`/`stable`/`current` for the BSDs.

**Comment by 4nd3r** [comment]
If you are using Sid, then you most probably know what you are doing and sometimes things break, because this is unstable or just somekind of change which requires me to adjust my own types.

Using next major version number for Sid allows early detection of problems with skonfig types and adjustments can be made. And when stable release is finally cut, then skonfig types are already compatible and we don't have to go over all the types which have `x.99` version comparision somewhere.

Easiest way to detect Debian "pre-release version" is to check if `os_version` has `\/sid$`. At least for Debian. How it can be done for Ubuntu or Devuan, I don't know and right now `__apt_backports` do not do anything like that, but this would be logical addition. Should it be separate global explorer or every type tries to be clever on its own, is just matter of taste and right now I don't have one :smile:

**Comment by sideeffect42** [comment]
> And when stable release is finally cut, then skonfig types are already compatible and we don't have to go over all the types which have `x.99` version comparision somewhere.

There is no need to update the `x.99` version comparisons when a new version is released. The new version `x+1` will also satisfy `>= x.99`.

> Easiest way to detect Debian "pre-release version" is to check if `os_version` has `\/sid$`.

Eeeh, no? The `/sid` suffix is removed by the version explorer when the codename is replaced with the version number.
I also don't really want to add it because it makes processing `os_version` again more complex.

Let me explain using an example: I have a manifest to manage ejabberd. On stable releases I like to install the version from backports.
But then I also have test VMs where I want to test if my config will also work with the next release ahead of time.

So I have this check in it to only configure backports for stable releases:
```sh
read -r os <"${__global:?}/explorer/os"
case ${os}
in
	(debian|devuan)
		read -r os_version <"${__global:?}/explorer/os_version"
		read -r lsb_codename _ <"${__global:?}/explorer/lsb_codename"

		case ${os_version-}
		in
			(*.9[0-9])
				# testing, no backports
				;;
			(*)
				__apt_backports

				require=__apt_backports/ \
				__apt_pin erlang-backports \
					--package 'erlang*' \
					--distribution "${lsb_codename:?}-backports" \
					--priority 600

				require=__apt_pin/erlang-backports \
				__apt_pin ejabberd-backports \
					--package 'ejabberd*' \
					--distribution "${lsb_codename:?}-backports" \
					--priority 600

				ejabberd_pre_require=${ejabberd_pre_require-}${ejabberd_pre_require:+ }__apt_pin/ejabberd-backports
				ejabberd_pre_require=${ejabberd_pre_require-}${ejabberd_pre_require:+ }__apt_pin/erlang-backports
				;;
		esac
		...
esac

...

__ejabberd_server \
	--config-source "${__files:?}/ejabberd.yml"
```

Again, I'm not a "fan" of `x.99`; I'm agnostic if this check uses the `os_version` explorer or something else, but I don't want to remove `.99` and rewrite my scripts until a new, better method is implemented (whatever it may be).

**Comment by 4nd3r** [comment]
Alright, let's do it this way.

**Review by sideeffect42 — APPROVED** [review]

**Pull request merged**
